### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by thegeorgeous** [sensorflo/git-draw#3]
I am getting this issue when I run the script on git-draw's repo itself
`Error: git-draw.dot: syntax error in line 16 near '\'`

**Comment by sensorflo** [comment]
I just pushed a commit fixing the bug. But anyway -- git-draw is only intended to draw tiny toy repositories to learn Git's internal data structures. If you use git-draw on a real repository, even a small one such as git-draw, the resulting picture will be far too large.

**Comment by frakman1** [comment]
You should output to svg files. That way, even large repositories (even draw-git) would work.
I changed [this line ](https://github.com/sensorflo/git-draw/blob/master/git-draw#L712)
to 
`dot -Tsvg "$dotfilename" > "$imgfilename" || exit 1`
as well as the default file-name [here](https://github.com/sensorflo/git-draw/blob/master/git-draw#L201)
to 
`imgfilename=git-draw.svg`
and things looked a lot better.

**Comment by Albertoalzha1** [comment]
Utiliza Markdown para darle formato al archivo
